sudo: false

language: php

php:
- 7.0
- 7.1
- 7.2

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini

install:
- composer install

script:
- >
  echo;
  echo "Validating the composer.json";
  composer validate --no-check-all --no-check-lock --strict;

- >
  echo;
  echo "Linting all PHP files";
  find Classes/ includes/ public/ Tests/ -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l;

- >
  echo;
  echo "Running the unit tests";
  vendor/bin/phpunit Tests/Unit/;

- >
  echo;
  echo "Running PHP_CodeSniffer";
  vendor/bin/phpcs --standard=Configuration/PhpCodeSniffer/Standards/Insecurity/ Classes/ Tests/;
