sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install

script:
  # Run PHP lint on all PHP files.
  - find Classes/ includes/ public/ Tests/ -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # Check the coding style.
  - vendor/bin/phpcs --standard=Configuration/PhpCodeSniffer/Standards/Insecurity/ Classes/ Tests/
  # Run the tests.
  - vendor/bin/phpunit Tests/
